# Generated by Django 5.0.1 on 2024-01-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenteinmobiliario',
            name='cedula',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
