# Generated by Django 5.0.1 on 2024-01-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0002_agenteinmobiliario_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenteinmobiliario',
            name='cedula',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
