# Generated by Django 5.0.1 on 2024-01-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0004_alter_agenteinmobiliario_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenteinmobiliario',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agenteinmobiliario',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agenteinmobiliario',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agenteinmobiliario',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='agenteinmobiliario',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
