# Generated by Django 5.0.1 on 2024-01-31 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0006_alter_agenteinmobiliario_facebook_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenteinmobiliario',
            options={'verbose_name': 'Agente inmobiliario', 'verbose_name_plural': 'Agentes inmobiliario'},
        ),
    ]
