# Generated by Django 5.0.1 on 2024-02-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0007_alter_agenteinmobiliario_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenteinmobiliario',
            name='telefono',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
