# Generated by Django 5.0.1 on 2024-01-17 23:55

import django.db.models.deletion
import inmuebles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0001_initial'),
        ('inmuebles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FotoInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=inmuebles.models.FotoInmueble.foto_inmueble_path)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('ubicacion_google_maps', models.URLField(blank=True, null=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmuebles.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('habitaciones', models.PositiveIntegerField()),
                ('banos', models.PositiveIntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('puestos_estacionamiento', models.PositiveIntegerField(default=0)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentes.agenteinmobiliario')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmuebles.estadoinmueble')),
                ('fotos', models.ManyToManyField(related_name='inmuebles', to='inmuebles.fotoinmueble')),
                ('ubicacion_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmuebles.direccion')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmuebles.tipoinmueble')),
            ],
        ),
        migrations.AddField(
            model_name='fotoinmueble',
            name='inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_inmueble', to='inmuebles.inmueble'),
        ),
    ]
