# Generated by Django 5.0.1 on 2024-01-31 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='direccion',
            options={'verbose_name': 'Dirección', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='estadoinmueble',
            options={'verbose_name': 'Estado de inmueble', 'verbose_name_plural': 'Estados de inmueble'},
        ),
        migrations.AlterModelOptions(
            name='inmueble',
            options={'verbose_name': 'Inmueble', 'verbose_name_plural': 'Inmuebles'},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'verbose_name': 'Municipio', 'verbose_name_plural': 'Municipios'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'Pais', 'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='parroquia',
            options={'verbose_name': 'Parroquia', 'verbose_name_plural': 'Parroquias'},
        ),
        migrations.AlterModelOptions(
            name='tipoinmueble',
            options={'verbose_name': 'Tipo de inmueble', 'verbose_name_plural': 'Tipos de inmueble'},
        ),
        migrations.AlterModelOptions(
            name='tipotransaccion',
            options={'verbose_name': 'Tipo transacción', 'verbose_name_plural': 'Tipos de transacción'},
        ),
    ]
