# Generated by Django 5.0.1 on 2024-02-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0002_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='incluido',
            field=models.CharField(choices=[('Si', 'Sí'), ('No', 'No')], default='Si', max_length=2),
        ),
    ]
