# Generated by Django 5.0.1 on 2024-01-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0002_estadoinmueble_fotoinmueble_tipoinmueble_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='descripcion',
            field=models.TextField(unique=True),
        ),
    ]
