# Generated by Django 5.0.1 on 2024-02-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0003_alter_servicio_incluido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='incluido',
            field=models.BooleanField(default=True),
        ),
    ]
