# Generated by Django 5.0.1 on 2024-02-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0003_imageninmueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(null=True, upload_to='inmuebles'),
        ),
    ]
