# Generated by Django 5.0.1 on 2024-01-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0003_alter_direccion_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='ubicacion_google_maps',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
