# Generated by Django 5.0.1 on 2024-02-02 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0004_inmueble_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='imagen',
        ),
    ]
