# Generated by Django 5.0.1 on 2024-01-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0004_alter_direccion_ubicacion_google_maps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
