# Generated by Django 5.0.1 on 2024-02-05 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0005_inmueble_creado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='creado_por',
        ),
    ]
