# Generated by Django 5.0.1 on 2024-02-03 00:13

import inmuebles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0005_remove_inmueble_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageninmueble',
            options={'verbose_name_plural': 'Imagenes del Inmueble'},
        ),
        migrations.AlterField(
            model_name='imageninmueble',
            name='imagen',
            field=models.ImageField(upload_to=inmuebles.models.nombrar_imagen_inmueble),
        ),
    ]
