# Generated by Django 5.0.1 on 2024-01-19 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0006_tipotransaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='transaccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inmuebles.tipotransaccion'),
            preserve_default=False,
        ),
    ]
