# Generated by Django 5.0.1 on 2024-02-06 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0004_alter_agenteinmobiliario_usuario'),
        ('inmuebles', '0006_remove_inmueble_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='agente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agentes.agenteinmobiliario'),
        ),
    ]
