# Generated by Django 5.0.1 on 2024-01-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0007_inmueble_transaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
