# Generated by Django 5.0.1 on 2024-01-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0008_inmueble_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='fotos',
            field=models.ManyToManyField(blank=True, null=True, related_name='inmuebles', to='inmuebles.fotoinmueble'),
        ),
    ]
