# Generated by Django 5.0.1 on 2024-01-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0009_alter_inmueble_fotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='fotos',
            field=models.ManyToManyField(related_name='inmuebles', to='inmuebles.fotoinmueble'),
        ),
    ]
