# Generated by Django 5.0.1 on 2024-02-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionempresa',
            name='maps',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
