# Generated by Django 5.0.1 on 2024-02-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_informacionempresa_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionempresa',
            name='descripcion_boletin',
            field=models.TextField(default='Destino Punta te invita a suscribirte a nuestro boletín informativo, donde podrás encontrar las últimas noticias y tendencias del mercado inmobiliario, así como ofertas exclusivas y descuentos especiales.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informacionempresa',
            name='title_boletin',
            field=models.CharField(default='Descubre las mejores ofertas y oportunidades del mercado inmobiliario', max_length=255),
            preserve_default=False,
        ),
    ]
