# Generated by Django 5.0.1 on 2024-02-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_informacionempresa_descripcion_boletin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionempresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='Empresa/'),
        ),
    ]
