# Generated by Django 5.0.1 on 2024-02-01 17:53

import empresa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_informacionempresa_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionempresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=empresa.models.nombrarLogo),
        ),
    ]
