# Generated by Django 5.0.1 on 2024-02-01 19:15

import empresa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_alter_informacionempresa_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionempresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=empresa.models.nombrar_logo),
        ),
    ]
