# Generated by Django 5.0.1 on 2024-02-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0011_informacionempresa_msj_asesores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionempresa',
            name='msj_asesores',
            field=models.TextField(default='Para cualquier consulta sobre nuestros exclusivos inmuebles o para recibir asesoramiento personalizado, no dude en ponerse en contacto con nuestra experta,'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informacionempresa',
            name='msj_whatsapp',
            field=models.TextField(default='¡Bienvenid@ a Destino Punta, su inmobiliaria de confianza! Aquí, hacemos realidad sus sueños de hogar.'),
            preserve_default=False,
        ),
    ]
